--data.lua

require("util-generic")
require("signal")
require("item-groups")
require("buildings")
require("item")
require("recipes")
require("technology")
require("resources")
require("tiles")
require("weapons")
require("ammo")
require("enemies")
require("vehicles")
require("turrets")
require("drills")
require("categories")
require("player")
require("movement_triggers")
require("equipment")
require("robots")
require("walls")
require("crashsite")
require("stats")
require("veteran-turrets")
require("rocks")
require("explosions")
require("map-gen-presets")
require("abandonments")
require("abandonments-noise-expressions")
require("collision-masks")

if (mods["space-age"]) then
require("recipes-sa")
require("item-sa")
require("technology-sa")
require("entities-sa")
require("buildings-sa")
end

require("blanket-data-updates")